Bridge.assembly("PythonLibQx", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = ["System","VistaLibQx.qx.interfaces","VistaLibQx.qx.ui.embed","VistaLibQx.util","PythonLibQx.app.ui.windows","VistaLibQx.qx.ui.basic","VistaLibQx.qx.ui.widgets.navbar","PythonLibQx.app.ui.container","PythonLibQx.app.util","PythonLibQx.app.api","PythonLibQx.app.messages","System.Collections.Generic"];
    $m("PythonLibQx.app.util.DelayUtil", function () { return {"att":1048961,"a":2,"s":true,"m":[{"a":2,"n":"Run","is":true,"t":8,"pi":[{"n":"process","pt":Function,"ps":0},{"n":"delay","pt":$n[0].Int32,"ps":1}],"sn":"Run","rt":$n[0].Void,"p":[Function,$n[0].Int32]}]}; }, $n);
    $m("PythonLibQx.app.util.EncodingUtil", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Unicode2Ascii","is":true,"t":8,"pi":[{"n":"unicodeString","pt":$n[0].String,"ps":0}],"sn":"Unicode2Ascii","rt":$n[0].String,"p":[$n[0].String]}]}; }, $n);
    $m("PythonLibQx.app.util.Message", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[0].String,$n[0].Object],"pi":[{"n":"action","pt":$n[0].String,"ps":0},{"n":"arg","pt":$n[0].Object,"ps":1}],"sn":"ctor"},{"a":2,"n":"_action","t":4,"rt":$n[0].String,"sn":"_action"},{"a":2,"n":"_arg","t":4,"rt":$n[0].Object,"sn":"_arg"}]}; }, $n);
    $m("PythonLibQx.app.util.ServiceUtil", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Base64Decode","t":8,"pi":[{"n":"base64EncodedData","pt":$n[0].String,"ps":0}],"sn":"Base64Decode","rt":$n[0].String,"p":[$n[0].String]},{"a":2,"n":"Base64Encode","t":8,"pi":[{"n":"plainText","pt":$n[0].String,"ps":0}],"sn":"Base64Encode","rt":$n[0].String,"p":[$n[0].String]},{"a":2,"n":"DecodeJson64","t":8,"pi":[{"n":"json64Str","pt":$n[0].String,"ps":0}],"sn":"DecodeJson64","rt":System.Object,"p":[$n[0].String]},{"a":2,"n":"EncodeRequest","t":8,"pi":[{"n":"id","pt":$n[0].Int32,"ps":0},{"n":"service","pt":$n[0].String,"ps":1},{"n":"method","pt":$n[0].String,"ps":2},{"n":"args","pt":System.Array.type(System.Object),"ps":3}],"sn":"EncodeRequest","rt":$n[0].String,"p":[$n[0].Int32,$n[0].String,$n[0].String,System.Array.type(System.Object)]},{"a":2,"n":"FilesListRequest","t":8,"pi":[{"n":"id","pt":$n[0].Int32,"ps":0},{"n":"path","pt":$n[0].String,"ps":1}],"sn":"FilesListRequest","rt":$n[0].String,"p":[$n[0].Int32,$n[0].String]},{"a":2,"n":"FilesReadRequest","t":8,"pi":[{"n":"id","pt":$n[0].Int32,"ps":0},{"n":"path","pt":$n[0].String,"ps":1}],"sn":"FilesReadRequest","rt":$n[0].String,"p":[$n[0].Int32,$n[0].String]},{"a":2,"n":"PythonEvalRequest","t":8,"pi":[{"n":"id","pt":$n[0].Int32,"ps":0},{"n":"expr","pt":$n[0].String,"ps":1}],"sn":"PythonEvalRequest","rt":$n[0].String,"p":[$n[0].Int32,$n[0].String]}]}; }, $n);
    $m("PythonLibQx.app.ui.windows.PythonClassBrowserWindow", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[1].IDesktopApi],"pi":[{"n":"vmApi","pt":$n[1].IDesktopApi,"ps":0}],"sn":"ctor"},{"ov":true,"a":3,"n":"DefaultCaption","t":8,"sn":"DefaultCaption","rt":$n[0].String}]}; }, $n);
    $m("PythonLibQx.app.ui.windows.PythonConsoleWindow", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[1].IDesktopApi],"pi":[{"n":"vmApi","pt":$n[1].IDesktopApi,"ps":0}],"sn":"ctor"},{"ov":true,"a":3,"n":"CreateEditor","t":8,"sn":"CreateEditor","rt":$n[2].MonacoEditor},{"ov":true,"a":3,"n":"DefaultCaption","t":8,"sn":"DefaultCaption","rt":$n[0].String},{"ov":true,"a":3,"n":"VmEvalExpr","t":8,"pi":[{"n":"expr","pt":$n[0].String,"ps":0},{"n":"fn","pt":Function,"ps":1}],"sn":"VmEvalExpr","rt":$n[0].Void,"p":[$n[0].String,Function]},{"a":1,"n":"_ivmApi","t":4,"rt":$n[1].IDesktopApi,"sn":"_ivmApi"}]}; }, $n);
    $m("PythonLibQx.app.ui.windows.PythonFileBrowserWindow", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[1].IFilesApi],"pi":[{"n":"fileApi","pt":$n[1].IFilesApi,"ps":0}],"sn":"ctor"},{"ov":true,"a":3,"n":"CreatePythonEditor","t":8,"sn":"CreatePythonEditor","rt":$n[2].MonacoEditor}]}; }, $n);
    $m("PythonLibQx.app.ui.windows.PythonTranscriptWindow", function () { return {"att":1048577,"a":2,"m":[{"a":1,"n":".ctor","t":1,"sn":"ctor"},{"a":3,"n":"ButtonConsole","t":8,"sn":"ButtonConsole","rt":$n[3].ButtonConfig},{"a":3,"n":"ButtonFiles","t":8,"sn":"ButtonFiles","rt":$n[3].ButtonConfig},{"ov":true,"a":3,"n":"DefaultButtons","t":8,"sn":"DefaultButtons","rt":System.Array.type(VistaLibQx.util.ButtonConfig)},{"ov":true,"a":3,"n":"DefaultCaption","t":8,"sn":"DefaultCaption","rt":$n[0].String},{"ov":true,"a":2,"n":"HandleEvent","t":8,"pi":[{"n":"eventName","pt":$n[0].String,"ps":0}],"sn":"HandleEvent","rt":$n[0].Void,"p":[$n[0].String]},{"a":2,"n":"Open","is":true,"t":8,"sn":"Open","rt":$n[0].Void},{"a":3,"n":"OpenConsole","t":8,"sn":"OpenConsole","rt":$n[0].Void},{"a":3,"n":"OpenFiles","t":8,"sn":"OpenFiles","rt":$n[0].Void},{"a":2,"n":"Instance","is":true,"t":16,"rt":$n[4].PythonTranscriptWindow,"g":{"a":2,"n":"get_Instance","t":8,"rt":$n[4].PythonTranscriptWindow,"fg":"Instance","is":true},"fn":"Instance"},{"a":1,"n":"_instance","is":true,"t":4,"rt":$n[4].PythonTranscriptWindow,"sn":"_instance"}]}; }, $n);
    $m("PythonLibQx.app.ui.widgets.navbar.PythonNavBar", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":3,"n":"AddLabel","t":8,"sn":"AddLabel","rt":$n[0].Void},{"ov":true,"a":3,"n":"CreateImage","t":8,"sn":"CreateImage","rt":$n[5].NavbarImage},{"ov":true,"a":3,"n":"CreateLabel","t":8,"sn":"CreateLabel","rt":$n[2].NavbarLabel},{"a":3,"n":"CreateVistaLogo","t":8,"sn":"CreateVistaLogo","rt":$n[5].NavbarImage},{"ov":true,"a":3,"n":"DefaultBackgroundColor","t":8,"sn":"DefaultBackgroundColor","rt":$n[0].String},{"ov":true,"a":3,"n":"DefaultPadding","t":8,"sn":"DefaultPadding","rt":$n[0].Array.type(System.Int32)},{"a":1,"n":"_vistaLogo","t":4,"rt":$n[5].NavbarImage,"sn":"_vistaLogo"}]}; }, $n);
    $m("PythonLibQx.app.ui.embed.PythonEditor", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; }, $n);
    $m("PythonLibQx.app.ui.embed.PythonNavBarLabel", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":3,"n":"DefaultHeight","t":8,"sn":"DefaultHeight","rt":$n[0].Int32,"box":function ($v) { return Bridge.box($v, System.Int32);}},{"ov":true,"a":3,"n":"DefaultText","t":8,"sn":"DefaultText","rt":$n[0].String}]}; }, $n);
    $m("PythonLibQx.app.ui.container.Viewport", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[1].IDesktopApi],"pi":[{"n":"vmApi","pt":$n[1].IDesktopApi,"ps":0}],"sn":"ctor"},{"v":true,"a":3,"n":"DefaultCssClass","t":8,"sn":"DefaultCssClass","rt":$n[0].String},{"v":true,"a":3,"n":"DefaultNavBar","t":8,"sn":"DefaultNavBar","rt":$n[6].NavBar},{"ov":true,"a":3,"n":"Init","t":8,"sn":"Init","rt":$n[0].Void},{"a":2,"n":"Instance","is":true,"t":16,"rt":$n[7].Viewport,"g":{"a":2,"n":"get_Instance","t":8,"rt":$n[7].Viewport,"fg":"Instance","is":true},"s":{"a":2,"n":"set_Instance","t":8,"p":[$n[7].Viewport],"rt":$n[0].Void,"fs":"Instance","is":true},"fn":"Instance"},{"a":1,"n":"__Property__Initializer__Instance","is":true,"t":4,"rt":$n[7].Viewport,"sn":"__Property__Initializer__Instance"},{"a":1,"n":"_desktop","t":4,"rt":$n[2].HtmlEmbed,"sn":"_desktop"},{"a":2,"n":"_desktopApi","t":4,"rt":$n[1].IDesktopApi,"sn":"_desktopApi"},{"a":1,"n":"_navbar","t":4,"rt":$n[6].NavBar,"sn":"_navbar"},{"a":1,"backing":true,"n":"<Instance>k__BackingField","is":true,"t":4,"rt":$n[7].Viewport,"sn":"Instance"}]}; }, $n);
    $m("PythonLibQx.app.ui.basic.PythonVistaLogo", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":3,"n":"DefaultHeight","t":8,"sn":"DefaultHeight","rt":$n[0].Int32,"box":function ($v) { return Bridge.box($v, System.Int32);}},{"ov":true,"a":2,"n":"DefaultSource","t":8,"sn":"DefaultSource","rt":$n[0].String},{"ov":true,"a":3,"n":"DefaultWidth","t":8,"sn":"DefaultWidth","rt":$n[0].Int32,"box":function ($v) { return Bridge.box($v, System.Int32);}}]}; }, $n);
    $m("PythonLibQx.app.ui.basic.PythonNavbarImage", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":3,"n":"DefaultMargins","t":8,"sn":"DefaultMargins","rt":$n[0].Array.type(System.Int32)},{"ov":true,"a":3,"n":"DefaultSize","t":8,"sn":"DefaultSize","rt":$n[0].Int32,"box":function ($v) { return Bridge.box($v, System.Int32);}},{"ov":true,"a":2,"n":"DefaultSource","t":8,"sn":"DefaultSource","rt":$n[0].String}]}; }, $n);
    $m("PythonLibQx.app.messages.MessageDispatcher", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":1,"n":"MessagePrn","t":8,"pi":[{"n":"text","pt":$n[0].String,"ps":0}],"sn":"MessagePrn","rt":$n[0].Void,"p":[$n[0].String]},{"a":1,"n":"ProcessMessage","t":8,"pi":[{"n":"message","pt":$n[8].Message,"ps":0}],"sn":"ProcessMessage","rt":$n[0].Void,"p":[$n[8].Message]},{"a":2,"n":"ProcessMessages","t":8,"pi":[{"n":"messagesObj","pt":System.Object,"ps":0}],"sn":"ProcessMessages","rt":$n[0].Void,"p":[System.Object]}]}; }, $n);
    $m("PythonLibQx.app.constants.TimingConstants", function () { return {"att":1048961,"a":2,"s":true,"m":[{"a":2,"n":"ResponseDelay","is":true,"t":4,"rt":$n[0].Int32,"sn":"ResponseDelay","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":2,"n":"TranscriptDelay","is":true,"t":4,"rt":$n[0].Int32,"sn":"TranscriptDelay","box":function ($v) { return Bridge.box($v, System.Int32);}}]}; }, $n);
    $m("PythonLibQx.app.api.IronPythonApi", function () { return {"att":1048577,"a":2,"m":[{"a":1,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"EvalExpr","t":8,"pi":[{"n":"expr","pt":$n[0].String,"ps":0},{"n":"fn","pt":Function,"ps":1}],"sn":"EvalExpr","rt":$n[0].Void,"p":[$n[0].String,Function]},{"a":2,"n":"ListFiles","t":8,"pi":[{"n":"path","pt":$n[0].String,"ps":0},{"n":"fn","pt":Function,"ps":1}],"sn":"ListFiles","rt":$n[0].Void,"p":[$n[0].String,Function]},{"a":2,"n":"ProcessResponse","t":8,"pi":[{"n":"json64Str","pt":$n[0].String,"ps":0}],"sn":"ProcessResponse","rt":$n[0].Void,"p":[$n[0].String]},{"a":2,"n":"ReadFile","t":8,"pi":[{"n":"path","pt":$n[0].String,"ps":0},{"n":"fn","pt":Function,"ps":1}],"sn":"ReadFile","rt":$n[0].Void,"p":[$n[0].String,Function]},{"a":1,"n":"RegisterResponseHandler","t":8,"pi":[{"n":"fn","pt":Function,"ps":0}],"sn":"RegisterResponseHandler","rt":$n[0].Int32,"p":[Function],"box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":1,"n":"SendServiceRequest","t":8,"pi":[{"n":"jsonStr","pt":$n[0].String,"ps":0}],"sn":"SendServiceRequest","rt":$n[0].Void,"p":[$n[0].String]},{"a":2,"n":"Instance","is":true,"t":16,"rt":$n[9].IronPythonApi,"g":{"a":2,"n":"get_Instance","t":8,"rt":$n[9].IronPythonApi,"fg":"Instance","is":true},"fn":"Instance"},{"a":1,"n":"_instance","is":true,"t":4,"rt":$n[9].IronPythonApi,"sn":"_instance"},{"a":1,"n":"_messageDispatcher","t":4,"rt":$n[10].MessageDispatcher,"sn":"_messageDispatcher"},{"a":1,"n":"_requestCounter","t":4,"rt":$n[0].Int32,"sn":"_requestCounter","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":1,"n":"_responseMap","t":4,"rt":$n[11].Dictionary$2(System.Int32,Function),"sn":"_responseMap"},{"a":1,"n":"_serviceUtil","t":4,"rt":$n[8].ServiceUtil,"sn":"_serviceUtil"}]}; }, $n);
});
